[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

[target.i686-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-pc-windows-msvc]
linker = "lld-link.exe"

[target.x86_64-unknown-none]
rustflags = [
  "-C",
  "code-model=small",
]
